## Arquivo para simulações rest da api para o controller do sqs

### Endpoint para criar uma fila
POST http://localhost:3000/sqs/create HTTP/1.1
Content-Type: application/json

{
  "queueName": "mariani5"
}

### Endpoint para enviar uma mensagem
POST http://localhost:3000/sqs/send HTTP/1.1
Content-Type: application/json

{
  "queueName": "mariani5",
  "message": "ddddddddddddddddddddd"
}

### Endpoint para listar as mensagens

GET http://localhost:3000/sqs/receive?queueName=mariani5 HTTP/1.1
